
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXhOVEU1TVRJek5sb1hEVE16TURReE1qRTVNVEl6Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3VWCitGdGpuNzVnQlZoemlWcm1PNUVXb3JSbTZNR2lVYllRWk5sZTN6VWNnL3ZnOGJLTmRtZ3N2Wk93ZG1rd0JXY2gKbDNrdzByS3gwM0w1ZHBZdm5pTGo1bWFzYTZuWlZnUkVZb3ZNOWVzK2orbGxjdC9VbDhkYUZCa1Y5a0thTWF1LwpIUTV2MzJYK3cvVm5sVm1YaDJFQzhscVVQWGptdkhTYVJOcWllUkpkRm53aEhGV3NoakpGWnJ2VWwzcXV2RDhFCmZSSWFVc2Z1VmVyQ3ZBa1VUY0J1TWkySnhKejJtSThjNUtieldLUTNDMVhodEZaUnBWcjFjMjUvenFnUG5na1YKQ2dzVUNCRFE1SHZqZDVLTTNTMTBCbTVDaGMxYzlmMGJuZkVCRVJnOE4yNVY3VjdSaklVMk51VXpIUTJ6V3BjdApTUlQzSFVvL2NraUdwMDZkblNNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGVGhlNG12TEdxaUxGN1dzV2EwYSs0bU9mKzBNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRE1XS016cVJRd3NIWURHa0xvbgpNRVBqcWJiLzVhVTNtR3cwZVpJcnY2N2RuWlh3Q1o0ekZPRXU2SGgwcmxKS0E0TUFlNWg2UHNsWSt0Q0dZK1dLCjF6bUVLUU8yV3A2ZC9qaG1FRUhpL05uOUMyUk14UlZxU3BHZ2N5TUFkQlZkY2J4cWZFRGcrU1MzMlg0eHdtTDIKaHkrYUVGNEpreUpyZHc0eVY4eStXdlJTOFM4WVRSME9jSlZZMmZyczV3MnpjRlNHTnExVjNSRng5UDlhSzgvSwpqWnNHRTExRURjL1FZOG9uSW8wMzcvK2xCclNYRC9maVgxTVZCQTlNaU5KOWV5alBZalJ6YWtIOXJHL1hjRGtqCkxKUjFIUWxRMnp2ZFhCUXhoQVY3dHhwMUN2Q3ZhaXhhNDJZcCt0d3kwcmtzTW9rQ09oUkV1T2hyVHNpVzBDQjMKNDJFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://4a4c139f-8f68-4d07-9426-76dca8384fd6.eu-central-1.linodelke.net:443
  name: lke103007

users:
- name: lke103007-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IllCOHBOalVtR0g0bGVFZmpxV0pULTBQai1BX1N4X3ZDU0hXUmZsTWp1d2cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZ3ZkNzciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNjI5ODdjZjUtMGY4Ni00ZGM0LWFkNjUtN2M0MDg5YThmMTc3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.ALj63VQ8lrP3hWUr6K_OeVjMZzkEThqurFTy9yElH4c2RrtqRaFM0BWiFrrHBcN7H3eQ4C6SyU-5JTtPIYQzJ3YemuOI-drXNTDCV1g3u_drhOHAScRqR8TMkGpv0DPFGZoZqJAdBXrYeUWe2m1Tu2LJy3H_xTJJKI0mn3u9lqs2qqoaoSHPIa4DlivBoryqI32kUVuqrRq6LwWWVBk3KRzVsauVur-JEbj3-nr3Zq7Lkl7PHcYIqrJ1Ul7-qCi_HPV6C3o_mc0o-bz8DmXjD_4hIu78cl7kcl0tsvYoJ5cG2f10mErpYENqXLIzjt9_fq_D5Iui243McT1QnYA9NA

contexts:
- context:
    cluster: lke103007
    namespace: default
    user: lke103007-admin
  name: lke103007-ctx

current-context: lke103007-ctx
